# Include the base configuration from the main file.
include "application.conf"

# This block will OVERRIDE the 'db' block from the included file.
db {
    driver = ${DB_DRIVER}
    url = ${DB_URL}
    user = ${DB_USER}
    password = ${DB_PASSWORD}
}

ktor {
    deployment {
        # Ktor automatically listens to the PORT environment variable if present.
        port = ${?PORT}
    }
}